# Generated by Django 5.2.4 on 2025-07-20 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Layihənin Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tapşırıq Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('status', models.CharField(choices=[('todo', 'Görüləcək'), ('in_progress', 'İcra edilir'), ('done', 'Tamamlanıb')], default='todo', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son İcra Tarixi')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Təyin Edilən Şəxs')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='Layihə')),
            ],
            options={
                'verbose_name': 'Tapşırıq',
                'verbose_name_plural': 'Tapşırıqlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
