# Generated by Django 5.2.4 on 2025-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Açıqlama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2025-07-21', verbose_name='Son İcra Tarixi'),
            preserve_default=False,
        ),
    ]
